batch_size: 128
#batch_size: 128
epochs: 40
#epochs: 80
#xlr: 0.0001
lr: 0.001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: data

# Evaluation
model_path: 

# New additions
dropout_rate: 0.5
scheduler_step_size: 10
scheduler_gamma: 0.1
early_stopping_patience: 10
